### ISSUE TITLE
Нет поддержки темной темы для экрана Я Пэй

### ISSUE THREAD

**Issue by ivanglushko** [yandexmobile/yandex-pay-ios#1]
Привет 👋 
Для кнопки есть appearance с поведением .system там вроде все ок, меняется тема правильно. 
Но дальнейший экран не реагирует на смену темы. 
Всегда показывает светлую версию.

Думал там веб вью или див кит, но вроде SUI нативный. Если сложно починить то нам не критично наверное. 
<img src="https://github.com/yandexmobile/yandex-pay-ios/assets/36343782/838bf6fd-a365-4fdb-aec0-e466d0422f89" width=40%>

**Comment by ya-pay** [comment]
Спасибо за наблюдательность!
Мы работаем над темной темой, планируем отдать в релиз в конце июня/начала июля
