### ISSUE TITLE
Не работает интеграция через SPM

### ISSUE THREAD

**Issue by ivanglushko** [yandexmobile/yandex-pay-ios#2]
Снова я)
Я из команды [АСДК](https://opensource.tinkoff.ru/tinkoff-mobile-tech/tinkoff-asdk-ios) начал поднимать версию YandexPaySDK в связи с проблемами [PromiseKit](https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3) сборки на `Xcode 15.1`. Заметил что у вас появилась возможность интеграции по спм, к сожалению она - сломана.

### Как проверить:
- Сделать базовый проект в Xcode пустой
- Подключить через Package `YandexPaySDK`
- В файле `ViewController.swift` сделать `import YandexPaySDK`
- Запустить на симуляторе
- Профит ловим райнтайм краш 
```
dyld[15233]: Library not loaded: @rpath/VQSwiftProtobuf.framework/VQSwiftProtobuf
  Referenced from: <8A4DCB1D-DB82-3FAB-A65D-B821294D39EE> /Users/ivan/Library/Developer/Xcode/DerivedData/test-fseukebqnadjwadeurrcjwtvzaxn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK
  Reason: tried: '/Users/ivan/Library/Developer/Xcode/DerivedData/test-fseukebqnadjwadeurrcjwtvzaxn/Build/Products/Debug-iphonesimulator/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/Users/ivan/Library/Developer/Xcode/DerivedData/test-fseukebqnadjwadeurrcjwtvzaxn/Build/Products/Debug-iphonesimulator/PackageFrameworks/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/usr/lib/swift/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file, not in dyld cache), '/Users/ivan/Library/Developer/CoreSimulator/Devices/DA15BFC9-5BEF-4F4E-AD01-F2AEB90FFECA/data/Containers/Bundle/Application/99F88875-3D4A-4240-BEFF-27330F28FA9B/test.app/Frameworks/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/Users/ivan/Library/Developer/Xcode/DerivedData/test-fseukebqnadjwadeurrcjwtvzaxn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Frameworks/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/Users/ivan/Library/Developer/CoreSimulator/Devices/DA15BFC9-5BEF-4F4E-AD01-F2AEB90FFECA/data/Containers/Bundle/Application/Frameworks/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/Users/ivan/Library/Developer/CoreSimulator/Devices/DA15BFC9-5BEF-4F4E-AD01-F2AEB90FFECA/data/Containers/Bundle/Application/99F88875-3D4A-4240-BEFF-27330F28FA9B/test.app/Frameworks/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/Users/ivan/Library/Developer/CoreSimulator/Devices/DA15BFC9-5BEF-4F4E-AD01-F2AEB90FFECA/data/Containers/Bundle/Application/99F88875-3D4A-4240-BEFF-27330F28FA9B/test.app/Frameworks/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/VQSwiftProtobuf.framework/VQSwiftProtobuf' (no such file)
```
### Пожелания
- Если бандл идет через СПМ, то важно по аналогии дать 2 продукта - Static и Dynamic.
- Учесть работу с бандлом в SPM она там своеобразная. В общем стоит пройти флоу хеппи пас через спм. Хотя скорее всего проблем не будет (бинарь)

**Comment by ya-pay** [comment]
Добрый день! Проблема была в отсутствии зависимости Varioqub, добавили в Package.swift
Уже исправлено, версия 1.8.0

**Comment by ya-pay** [comment]
Для SPM пока нет возможности поставлять Static версию
Подскажите, она вам необходима в данный момент?
Также подсвечу, что у нас нет зависимости на PromiseKit

**Comment by ivanglushko** [comment]
> Для SPM пока нет возможности поставлять Static версию Подскажите, она вам необходима в данный момент? Также подсвечу, что у нас нет зависимости на PromiseKit



> Для SPM пока нет возможности поставлять Static версию

Там в целом и динамика не работает. 
PromiseKit у вас был в версии 1.3.6 с которой мы обновлялись.

**Comment by ivanglushko** [comment]
> Для SPM пока нет возможности поставлять Static версию Подскажите, она вам необходима в данный момент? Также подсвечу, что у нас нет зависимости на PromiseKit

Cпасибо проверим позже интеграцию по спм) Для нас некритична статика для спм.
PromiseKit был у вас в версии 1.3.6 с который я обновлялся.
