### ISSUE TITLE
Соблюдение Semantic Versioning

### ISSUE THREAD

**Issue by ivanglushko** [yandexmobile/yandex-pay-ios#3]
Привет)
Столкнулся с проблемами мисслидинга [semver](https://semver.org/)
Поднимал через кокоаподс сдк с версии 1.3.6 до версии 1.7.0
## Словил ошибки
<img width="1712" alt="Screenshot 2024-05-31 at 13 54 35" src="https://github.com/yandexmobile/yandex-pay-ios/assets/36343782/c568478a-690c-4172-913c-f199ae327630">

## Пожелания
По идее это ломающие изменения соотвественно нужно поднимать мажорку, чтобы не словить такое.
Понимаю что уследить за этим сложно, мы у себя используем пайплайны которые смотрят соблюдение Swift API/ABI совместимость. Автоматически подсвечивает правильно ли проставили версию бампа компонента.
Для этого используем [swift-api-digester](https://forums.swift.org/t/using-swift-api-digester/22956/3) может получиться и вам адаптировать.

**Comment by ya-pay** [comment]
Спасибо за наблюдательность еще раз!
Да, мы осознанно сейчас не соблюдаем semver, так как нам эффективнее делать релизы поднимая minor версию.
Мы очень редко меняем публичный API, будем стараться, чтобы в дальнейшем проблем с совместимостью было как можно меньше
