### ISSUE TITLE
Не собирается YandexPaySDK/Dynamic

### ISSUE THREAD

**Issue by ivanglushko** [yandexmobile/yandex-pay-ios#4]
Привет!
Если затягивать `pod 'YandexPaySDK/Dynamic', '1.7.0'` ловим рантайм краш.
Получаю аналогичную ошибку как тут https://github.com/yandexmobile/yandex-pay-ios/issues/2

Если [сранить сабспеку](https://github.com/CocoaPods/Specs/commit/d200474c63f609d95f65dd2c017cd8bdf58d305e) со статикой то можно найти различия.
Подозреваю что нужно также добавить:
- ресурсный бандл `"resources": "YandexPaySDK/Dynamic/YandexPaySDKResources.bundle",`
- зависимости 
```ruby
"dependencies": {
        "YandexLoginSDK": [
          "~> 2.1"
        ],
        "AppMetricaCore": [
          "~> 5.2"
        ],
        "Varioqub": [
          "~> 0.6"
        ]
 },
```

*Еще как вариант можно все забандлить в `.xcframework` но нужно собирать зависимости выше в `.xcframework` формат.*

**Comment by ivanglushko** [comment]
P.S: Нам не критично мы юзаем под со статикой, но возможно кому-то нужна именно динамика

**Comment by ya-pay** [comment]
Добрый день! Проблема была в отсутствии зависимости Varioqub в dynamic спеки
Уже исправлено, версия 1.8.0

**Comment by ivanglushko** [comment]
Cпасибо)
