### ISSUE TITLE
Документация не покрывает SceneDelegate

### ISSUE THREAD

**Issue by ivanglushko** [yandexmobile/yandex-pay-ios#5]
Начиная с iOS 13 в проектах может быть использован `SceneDelegate` тогда события шлются в него вместо `AppDelegate`
Нужно добавить этот кейс для [доки сюда](https://pay.yandex.ru/ru/docs/custom/ios-sdk/url-flow)
Единственное нужно будет клиенту сделать маппинг свойств объекта в словарь.
p.s `YandexPayApplicationEventsReceiver` - обертка которая проксирует вызовы к вашему сдк
<img width="966" alt="Screenshot 2024-05-31 at 19 10 56" src="https://github.com/yandexmobile/yandex-pay-ios/assets/36343782/a026f100-224b-4716-b28b-2ae832d28534">

**Comment by ya-pay** [comment]
Спасибо за совет!
В данном случае работа с AppDelegate почти аналогична работе с SceneDelegate
Мы обязательно доработаем нашу документацию для работы с SceneDelegate в июне/июле
