### ISSUE TITLE
Podfile проблема

### ISSUE THREAD

**Issue by ivanglushko** [yandexmobile/yandex-pay-ios#6]
Подобный хак может зафейлить сборку других зависимых от вашего пода подов.
https://github.com/yandexmobile/yandex-pay-ios/blob/3f56c81ed3e8d79ffc9d2a8f497b3a74a19ac3f3/Demo/Podfile#L14

**Comment by ya-pay** [comment]
Добрый день!
Это настройка только внутри нашего демо проекта
Этот скрипт фиксит проблему с кучей ворнингов из-за дефолтной версии iOS, если у вас возникли проблемы с другими зависимостями, напишите пожалуйста ниже, попробуем разобраться

**Comment by ivanglushko** [comment]
Да мы столкнулись с проблемой релиза нашей спеки в кокоаподс [из-за зависимости япэй](https://opensource.tinkoff.ru/tinkoff-mobile-tech/tinkoff-asdk-ios/-/blob/master/TASDKYandexPay.podspec?ref_type=heads#L24).
Проблема [следующего характера](https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d) 

Как я понимаю вы тоже работаете в Xcode 15.1 где минимальная версия сдк - ios 12.0 , но спеки от которых вы зависите тянут минимальную версию ios 11.0.
Так вот при попытки запушить нашу спеку, получали билд error указанный выше, к сожалению там никаких хуков нельзя проставить чтобы сгенерированный проект (при пуше спеки) использовал заданую версию minimum deployment target ios.
В итоге у меня удалось запушить секу (правда я не совсем понял как я это сделал)
Ну и игрался с [приватным репозиторием спек](https://github.com/ivanglushko/asdk-specs), где добавил нужные спеки и проставил им новую минимальную версию - 12.0.

**Comment by ivanglushko** [comment]
На данный момент у нас проблема нет, так как спеку удалось все таки запушить. Но наверное данный хак лучше убрать, чтобы ловить все ошибки в демке тоже.
